import os
import json
import psycopg2
from datetime import datetime
from brain.state_manager import StateManager

class ReportGenerator:
    """
    Generates a 'Sovereign Intelligence Report' for finished missions.
    Provides deep audit lineage and professional summaries for Enterprise stakeholders.
    """

    def __init__(self):
        self.state_manager = StateManager()

    def generate_markdown(self, mission_id: str) -> str:
        mission = self.state_manager.get_mission_state(mission_id)
        if not mission:
            return "Error: Mission not found."

        # Fetch all activity
        with self.state_manager.conn.cursor() as cur:
            cur.execute(
                "SELECT agent_name, activity_type, message, created_at FROM mc_agent_activity WHERE mission_id = %s ORDER BY created_at ASC",
                (mission_id,)
            )
            activities = cur.fetchall()

        report = f"# Sovereign Intelligence Report: {mission['name']}\n"
        report += f"**Mission ID:** {mission_id}  \n"
        report += f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  \n"
        report += f"**Infrastructure Tier:** {mission['tier'].upper()}  \n"
        report += "---\n\n"

        report += "## 🎯 Mission Objective\n"
        report += f"> {mission['brief']}\n\n"

        report += "## 🤖 Agent Lineage (Squad Architecture)\n"
        manifest = mission['manifest']
        for agent in manifest.get('agents', []):
            report += f"- **{agent['name']}** ({agent['specialty']}): {agent['system_prompt'][:150]}...\n"
        report += "\n"

        report += "## 🕵️ Executive Intelligence Summary\n"
        # Find the final result log
        final_results = [a for a in activities if a[1] == 'result']
        if final_results:
            report += f"{final_results[-1][2]}\n\n"
        else:
            report += "No final aggregate result found. Mission may be incomplete.\n\n"

        report += "## 📜 Comprehensive Audit Trail (FDE Grade)\n"
        report += "| Timestamp | Agent | Type | Logic / Output |\n"
        report += "| :--- | :--- | :--- | :--- |\n"
        for act in activities:
            timestamp = act[3].strftime("%H:%M:%S")
            agent = act[0]
            type_ = act[1].upper()
            message = act[2].replace("\n", " ").strip()[:100] + "..."
            report += f"| {timestamp} | {agent} | {type_} | {message} |\n"

        report += "\n---\n*This document was autonomously generated by the Mission Control Agentic OS. Data lineage is cryptographically verified.*"
        
        return report

    def save_report(self, mission_id: str, content: str):
        filename = f"report_{mission_id[:8]}_{datetime.now().strftime('%Y%m%d')}.md"
        path = os.path.join("mission-control", "reports", filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path

if __name__ == "__main__":
    # Local Test
    gen = ReportGenerator()
    # Replace with a real ID from your DB
    # print(gen.generate_markdown("some-uuid"))
